package com.willendless.nes.emulator.cpu

import com.willendless.nes.emulator.cpu.AddressMode.*

@ExperimentalUnsignedTypes
object OpcodeMap {
    @ExperimentalUnsignedTypes
    data class Opcode(val code: UByte, val name: String, val len: UShort,
                      val mode: AddressMode, val cycles: Int,
                      val pageCrossedOverhead: Boolean = false,
                      val branch: Boolean = false)

    private val opcodesList = arrayListOf<Opcode>(
            Opcode(0xe8u, "INX", 1u, NoneAddressing, 2),
            // LDA
            Opcode(0xa9u, "LDA", 2u, Immediate, 2),
            Opcode(0xa5u, "LDA", 2u, ZeroPage, 3),
            Opcode(0xb5u, "LDA", 2u, ZeroPageX, 4),
            Opcode(0xadu, "LDA", 3u, Absolute, 4),
            Opcode(0xbdu, "LDA", 3u, AbsoluteX, 4, true),
            Opcode(0xb9u, "LDA", 3u, AbsoluteY, 4, true),
            Opcode(0xa1u, "LDA", 2u, IndirectX, 6),
            Opcode(0xb1u, "LDA", 2u, IndirectY, 5, true),
            // LDX
            Opcode(0xa2u, "LDX", 2u, Immediate, 2),
            Opcode(0xa6u, "LDX", 2u, ZeroPage, 3),
            Opcode(0xb6u, "LDX", 2u, ZeroPageY, 4),
            Opcode(0xaeu, "LDX", 3u, Absolute, 4),
            Opcode(0xbeu, "LDX", 3u, AbsoluteY, 4, true),
            // LDY
            Opcode(0xA0u, "LDY", 2u, Immediate, 2),
            Opcode(0xA4u, "LDY", 2u, ZeroPage, 3),
            Opcode(0xB4u, "LDY", 2u, ZeroPageX, 4),
            Opcode(0xAcu, "LDY", 3u, Absolute, 4),
            Opcode(0xBCu, "LDY", 3u, AbsoluteX, 4,  true),
            // LAX
            Opcode(0xA7u, "*LAX", 2u, ZeroPage, 3),
            Opcode(0xB7u, "*LAX", 2u, ZeroPageY, 4),
            Opcode(0xAFu, "*LAX", 3u, Absolute, 4),
            Opcode(0xBFu, "*LAX", 3u, AbsoluteY, 4, true),
            Opcode(0xA3u, "*LAX", 2u, IndirectX, 6),
            Opcode(0xB3u, "*LAX", 2u, IndirectY, 5, true),
            // STA
            Opcode(0x85u, "STA", 2u, ZeroPage, 3),
            Opcode(0x95u, "STA", 2u, ZeroPageX, 4),
            Opcode(0x8Du, "STA", 3u, Absolute, 4),
            Opcode(0x9Du, "STA", 3u, AbsoluteX, 5),
            Opcode(0x99u, "STA", 3u, AbsoluteY, 5),
            Opcode(0x81u, "STA", 2u, IndirectX, 6),
            Opcode(0x91u, "STA", 2u, IndirectY, 6),
            // STX
            Opcode(0x86u, "STX", 2u, ZeroPage, 3),
            Opcode(0x96u, "STX", 2u, ZeroPageY, 4),
            Opcode(0x8Eu, "STX", 3u, Absolute, 4),
            // STY
            Opcode(0x84u, "STY", 2u, ZeroPage, 3),
            Opcode(0x94u, "STY", 2u, ZeroPageX, 4),
            Opcode(0x8Cu, "STY", 3u, Absolute, 4),
            // Register Transfer
            Opcode(0xaau, "TAX", 1u, NoneAddressing, 2),
            Opcode(0xA8u, "TAY", 1u, NoneAddressing, 2),
            Opcode(0xBAu, "TSX", 1u, NoneAddressing, 2),
            Opcode(0x8Au, "TXA", 1u, NoneAddressing, 2),
            Opcode(0x9Au, "TXS", 1u, NoneAddressing, 2),
            Opcode(0x98u, "TYA", 1u, NoneAddressing, 2),
            // Stack push & pop
            Opcode(0x48u, "PHA", 1u, NoneAddressing, 3),
            Opcode(0x08u, "PHP", 1u, NoneAddressing, 3),
            Opcode(0x68u, "PLA", 1u, NoneAddressing, 4),
            Opcode(0x28u, "PLP", 1u, NoneAddressing, 4),
            // Logical Operations
            Opcode(0x29u, "AND", 2u, Immediate, 2),
            Opcode(0x25u, "AND", 2u, ZeroPage, 3),
            Opcode(0x35u, "AND", 2u, ZeroPageX, 4),
            Opcode(0x2Du, "AND", 3u, Absolute, 4),
            Opcode(0x3Du, "AND", 3u, AbsoluteX, 4, true),
            Opcode(0x39u, "AND", 3u, AbsoluteY, 4, true),
            Opcode(0x21u, "AND", 2u, IndirectX, 6),
            Opcode(0x31u, "AND", 2u, IndirectY, 5),
            Opcode(0x09u, "ORA", 2u, Immediate, 2),
            Opcode(0x05u, "ORA", 2u, ZeroPage, 3),
            Opcode(0x15u, "ORA", 2u, ZeroPageX, 4),
            Opcode(0x0Du, "ORA", 3u, Absolute, 4),
            Opcode(0x1Du, "ORA", 3u, AbsoluteX, 4, true),
            Opcode(0x19u, "ORA", 3u, AbsoluteY, 4, true),
            Opcode(0x01u, "ORA", 2u, IndirectX, 6),
            Opcode(0x11u, "ORA", 2u, IndirectY, 5, true),
            Opcode(0x49u, "EOR", 2u, Immediate, 2),
            Opcode(0x45u, "EOR", 2u, ZeroPage, 3),
            Opcode(0x55u, "EOR", 2u, ZeroPageX, 4),
            Opcode(0x4Du, "EOR", 3u, Absolute, 4),
            Opcode(0x5Du, "EOR", 3u, AbsoluteX, 4, true),
            Opcode(0x59u, "EOR", 3u, AbsoluteY, 4, true),
            Opcode(0x41u, "EOR", 2u, IndirectX, 6),
            Opcode(0x51u, "EOR", 2u, IndirectY, 5, true),
            Opcode(0x24u, "BIT", 2u, ZeroPage, 3),
            Opcode(0x2Cu, "BIT", 3u, Absolute, 4),
            Opcode(0xC9u, "CMP", 2u, Immediate, 2),
            Opcode(0xC5u, "CMP", 2u, ZeroPage, 3),
            Opcode(0xD5u, "CMP", 2u, ZeroPageX, 4),
            Opcode(0xCDu, "CMP", 3u, Absolute, 4),
            Opcode(0xDDu, "CMP", 3u, AbsoluteX, 4, true),
            Opcode(0xD9u, "CMP", 3u, AbsoluteY, 4, true),
            Opcode(0xC1u, "CMP", 2u, IndirectX, 6),
            Opcode(0xD1u, "CMP", 2u, IndirectY, 5, true),
            Opcode(0xE0u, "CPX", 2u, Immediate, 2),
            Opcode(0xE4u, "CPX", 2u, ZeroPage, 3),
            Opcode(0xECu, "CPX", 3u, Absolute, 4),
            Opcode(0xC0u, "CPY", 2u, Immediate, 2),
            Opcode(0xC4u, "CPY", 2u, ZeroPage, 3),
            Opcode(0xCCu, "CPY", 3u, Absolute, 4),
            Opcode(0x87u, "*SAX", 2u, ZeroPage, 3),
            Opcode(0x97u, "*SAX", 2u, ZeroPageY, 4),
            Opcode(0x83u, "*SAX", 2u, IndirectX, 6),
            Opcode(0x8Fu, "*SAX", 3u, Absolute, 4),
            // Arithmetic Operations
            Opcode(0x69u, "ADC", 2u, Immediate, 2),
            Opcode(0x65u, "ADC", 2u, ZeroPage, 3),
            Opcode(0x75u, "ADC", 2u, ZeroPageX, 4),
            Opcode(0x6Du, "ADC", 3u, Absolute, 4),
            Opcode(0x7Du, "ADC", 3u, AbsoluteX, 4, true),
            Opcode(0x79u, "ADC", 3u, AbsoluteY, 4, true),
            Opcode(0x61u, "ADC", 2u, IndirectX, 6),
            Opcode(0x71u, "ADC", 2u, IndirectY, 5, true),
            Opcode(0xE9u, "SBC", 2u, Immediate, 2),
            Opcode(0xEBu, "*SBC", 2u, Immediate, 2),
            Opcode(0xE5u, "SBC", 2u, ZeroPage, 3),
            Opcode(0xF5u, "SBC", 2u, ZeroPageX, 4),
            Opcode(0xEDu, "SBC", 3u, Absolute, 4),
            Opcode(0xFDu, "SBC", 3u, AbsoluteX, 4, true),
            Opcode(0xF9u, "SBC", 3u, AbsoluteY, 4, true),
            Opcode(0xE1u, "SBC", 2u, IndirectX, 6),
            Opcode(0xF1u, "SBC", 2u, IndirectY, 5, true),
            // Inc & Dec
            Opcode(0xE6u, "INC", 2u, ZeroPage, 5),
            Opcode(0xF6u, "INC", 2u, ZeroPageX, 6),
            Opcode(0xEEu, "INC", 3u, Absolute, 6),
            Opcode(0xFEu, "INC", 3u, AbsoluteX, 7),
            Opcode(0xE8u, "INX", 1u, NoneAddressing, 2),
            Opcode(0xC8u, "INY", 1u, NoneAddressing, 2),
            Opcode(0xC6u, "DEC", 2u, ZeroPage, 5),
            Opcode(0xD6u, "DEC", 2u, ZeroPageX, 6),
            Opcode(0xCEu, "DEC", 3u, Absolute, 6),
            Opcode(0xDEu, "DEC", 3u, AbsoluteX, 7),
            Opcode(0xCAu, "DEX", 1u, NoneAddressing, 2),
            Opcode(0x88u, "DEY", 1u, NoneAddressing, 2),
            Opcode(0xC7u, "*DCP", 2u, ZeroPage, 5),
            Opcode(0xD7u, "*DCP", 2u, ZeroPageX, 6),
            Opcode(0xCFu, "*DCP", 3u, Absolute, 6),
            Opcode(0xDFu, "*DCP", 3u, AbsoluteX, 7),
            Opcode(0xDBu, "*DCP", 3u, AbsoluteY, 7),
            Opcode(0xC3u, "*DCP", 2u, IndirectX, 8),
            Opcode(0xD3u, "*DCP", 2u, IndirectY, 8),
            Opcode(0xE7u, "*ISB", 2u, ZeroPage, 5),
            Opcode(0xF7u, "*ISB", 2u, ZeroPageX, 6),
            Opcode(0xEFu, "*ISB", 3u, Absolute, 6),
            Opcode(0xFFu, "*ISB", 3u, AbsoluteX, 7),
            Opcode(0xFBu, "*ISB", 3u, AbsoluteY, 7),
            Opcode(0xE3u, "*ISB", 2u, IndirectX, 8),
            Opcode(0xF3u, "*ISB", 2u, IndirectY, 8),
            // Shifts
            Opcode(0x0Au, "ASL", 1u, Accumulator, 2),
            Opcode(0x06u, "ASL", 2u, ZeroPage, 5),
            Opcode(0x16u, "ASL", 2u, ZeroPageX, 6),
            Opcode(0x0Eu, "ASL", 3u, Absolute, 6),
            Opcode(0x1Eu, "ASL", 3u, AbsoluteX, 7),
            Opcode(0x4Au, "LSR", 1u, Accumulator, 2),
            Opcode(0x46u, "LSR", 2u, ZeroPage, 5),
            Opcode(0x56u, "LSR", 2u, ZeroPageX, 6),
            Opcode(0x4Eu, "LSR", 3u, Absolute, 6),
            Opcode(0x5Eu, "LSR", 3u, AbsoluteX, 7),
            Opcode(0x2Au, "ROL", 1u, Accumulator, 2),
            Opcode(0x26u, "ROL", 2u, ZeroPage, 5),
            Opcode(0x36u, "ROL", 2u, ZeroPageX, 6),
            Opcode(0x2Eu, "ROL", 3u, Absolute, 6),
            Opcode(0x3Eu, "ROL", 3u, AbsoluteX, 7),
            Opcode(0x6Au, "ROR", 1u, Accumulator, 2),
            Opcode(0x66u, "ROR", 2u, ZeroPage, 5),
            Opcode(0x76u, "ROR", 2u, ZeroPageX, 6),
            Opcode(0x6Eu, "ROR", 3u, Absolute, 6),
            Opcode(0x7Eu, "ROR", 3u, AbsoluteX, 7),
            Opcode(0x07u, "*SLO", 2u, ZeroPage, 5),
            Opcode(0x17u, "*SLO", 2u, ZeroPageX, 6),
            Opcode(0x0Fu, "*SLO", 3u, Absolute, 6),
            Opcode(0x1Fu, "*SLO", 3u, AbsoluteX, 7),
            Opcode(0x1Bu, "*SLO", 3u, AbsoluteY, 7),
            Opcode(0x03u, "*SLO", 2u, IndirectX, 8),
            Opcode(0x13u, "*SLO", 2u, IndirectY, 8),
            Opcode(0x27u, "*RLA", 2u, ZeroPage, 5),
            Opcode(0x37u, "*RLA", 2u, ZeroPageX, 6),
            Opcode(0x2Fu, "*RLA", 3u, Absolute, 6),
            Opcode(0x3Fu, "*RLA", 3u, AbsoluteX, 7),
            Opcode(0x3Bu, "*RLA", 3u, AbsoluteY, 7),
            Opcode(0x23u, "*RLA", 2u, IndirectX, 8),
            Opcode(0x33u, "*RLA", 2u, IndirectY, 8),
            Opcode(0x47u, "*SRE", 2u, ZeroPage, 5),
            Opcode(0x57u, "*SRE", 2u, ZeroPageX, 6),
            Opcode(0x4Fu, "*SRE", 3u, Absolute, 6),
            Opcode(0x5Fu, "*SRE", 3u, AbsoluteX, 7),
            Opcode(0x5Bu, "*SRE", 3u, AbsoluteY, 7),
            Opcode(0x43u, "*SRE", 2u, IndirectX, 8),
            Opcode(0x53u, "*SRE", 2u, IndirectY, 8),
            Opcode(0x67u, "*RRA", 2u, ZeroPage, 5),
            Opcode(0x77u, "*RRA", 2u, ZeroPageX, 6),
            Opcode(0x6Fu, "*RRA", 3u, Absolute, 6),
            Opcode(0x7Fu, "*RRA", 3u, AbsoluteX, 7),
            Opcode(0x7Bu, "*RRA", 3u, AbsoluteY, 7),
            Opcode(0x63u, "*RRA", 2u, IndirectX, 8),
            Opcode(0x73u, "*RRA", 2u, IndirectY, 8),
            // Jumps & Calls
            Opcode(0x4Cu, "JMP", 3u, Absolute, 3),
            Opcode(0x6Cu, "JMP", 3u, Indirect, 5),
            Opcode(0x20u, "JSR", 3u, Absolute, 6),
            Opcode(0x60u, "RTS", 1u, NoneAddressing, 6),
            // Branches
            Opcode(0x90u, "BCC", 2u, Relative, 2, true, true),
            Opcode(0xB0u, "BCS", 2u, Relative, 2, true, true),
            Opcode(0xF0u, "BEQ", 2u, Relative, 2, true, true),
            Opcode(0x30u, "BMI", 2u, Relative, 2, true,  true),
            Opcode(0xD0u, "BNE", 2u, Relative, 2, true, true),
            Opcode(0x10u, "BPL", 2u, Relative, 2, true, true),
            Opcode(0x50u, "BVC", 2u, Relative, 2, true, true),
            Opcode(0x70u, "BVS", 2u, Relative, 2, true, true),
            // Status Flag Changes
            Opcode(0x18u, "CLC", 1u, NoneAddressing, 2),
            Opcode(0xD8u, "CLD", 1u, NoneAddressing, 2),
            Opcode(0x58u, "CLI", 1u, NoneAddressing, 2),
            Opcode(0xB8u, "CLV", 1u, NoneAddressing, 2),
            Opcode(0x38u, "SEC", 1u, NoneAddressing, 2),
            Opcode(0xF8u, "SED", 1u, NoneAddressing, 2),
            Opcode(0x78u, "SEI", 1u, NoneAddressing, 2),
            // System Functions
            Opcode(0x00u, "BRK", 1u, NoneAddressing, 7),
            Opcode(0xEAu, "NOP", 1u, NoneAddressing, 2),
            Opcode(0x1Au, "*NOP", 1u, NoneAddressing, 2),
            Opcode(0x3Au, "*NOP", 1u, NoneAddressing, 2),
            Opcode(0x5Au, "*NOP", 1u, NoneAddressing, 2),
            Opcode(0x7Au, "*NOP", 1u, NoneAddressing, 2),
            Opcode(0xDAu, "*NOP", 1u, NoneAddressing, 2),
            Opcode(0xFAu, "*NOP", 1u, NoneAddressing, 2),
            Opcode(0x04u, "*NOP", 2u, ZeroPage, 3),
            Opcode(0x14u, "*NOP", 2u, ZeroPageX, 4),
            Opcode(0x34u, "*NOP", 2u, ZeroPageX, 4),
            Opcode(0x44u, "*NOP", 2u, ZeroPage, 3),
            Opcode(0x54u, "*NOP", 2u, ZeroPageX, 4),
            Opcode(0x64u, "*NOP", 2u, ZeroPage, 3),
            Opcode(0x74u, "*NOP", 2u, ZeroPageX, 4),
            Opcode(0x80u, "*NOP", 2u, Immediate, 2),
            Opcode(0x82u, "*NOP", 2u, Immediate, 2),
            Opcode(0x89u, "*NOP", 2u, Immediate, 2),
            Opcode(0xC2u, "*NOP", 2u, Immediate, 2),
            Opcode(0xD4u, "*NOP", 2u, ZeroPageX, 4),
            Opcode(0xE2u, "*NOP", 2u, Immediate, 2),
            Opcode(0xF4u, "*NOP", 2u, ZeroPageX, 4),
            Opcode(0x0Cu, "*NOP", 3u, Absolute, 4),
            Opcode(0x1Cu, "*NOP", 3u, AbsoluteX, 4, true),
            Opcode(0x3Cu, "*NOP", 3u, AbsoluteX, 4, true),
            Opcode(0x5Cu, "*NOP", 3u, AbsoluteX, 4, true),
            Opcode(0x7Cu, "*NOP", 3u, AbsoluteX, 4, true),
            Opcode(0xDCu, "*NOP", 3u, AbsoluteX, 4, true),
            Opcode(0xFCu, "*NOP", 3u, AbsoluteX, 4, true),
            Opcode(0x40u, "RTI", 1u, NoneAddressing, 6)
    )

    private val opcodes = HashMap<UByte, Opcode>().apply {
        for (opcode in opcodesList) {
            this[opcode.code] = opcode
        }
    }

    fun getOpcode(code: UByte) = opcodes.getOrElse(code) { Opcode(
            code = 0x0u,
            name = "Unknown",
            len = 0u,
            mode = NoneAddressing,
            cycles = 0
    ) }
}